name: pypi_workflow
run-name: ${{ github.actor }} published to pypi
on: [push]
jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2

      - run: python -m pip install build --user
      - run: python -m build --sdist --wheel --outdir dist/ .
      